/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    BotonTema: typeof import('./src/components/BotonTema.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ModalEliminar: typeof import('./src/components/modales/ModalEliminar.vue')['default']
    ModalFormularios: typeof import('./src/components/modales/ModalFormularios.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Notificacion: typeof import('./src/components/Notificacion.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
